---
- hosts: localhost  
  gather_facts: false
  tasks:
    - block:
      - command: "ls /home/ansadmin/ans_workspace/playbooks"
        register: ouput
      - command: "ls /abc"  # Task going to fail
        register: abc
      - command: "ls /home/ansadmin"
        register: ansadmin
      ignore_errors: Yes  # this is applicable at block level now

   